#!/usr/bin/env node
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { loadConfig } from "./utils/config.js";
import { startStdio } from "./stdio.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function printHelp(): void {
  console.error(`universal-mcp-fs — local MCP filesystem + command execution server (stdio only)

Usage:
  universal-mcp-fs [options]

Quick Start:
  npm install -g universal-mcp-fs
  universal-mcp-fs-setup
  # Restart Claude Desktop — done!

Options:
  --allowed-dirs <dirs>       Semicolon-separated list of allowed directories
                               (default: your home directory)
  --disable-commands          Disable run_command / run_command_background tools
  --disable-delete            Disable delete_file / delete_directory tools
  --max-file-size <bytes>     Max readable file size (default: 10485760)
  --command-timeout <ms>      Default timeout for run_command (default: 30000)
  --elicitation-timeout <ms>  Timeout for approval popups (default: 120000)
  --max-search-results <n>    Cap on search tool results (default: 50)
  --version                   Print version and exit
  --help                      Show this help and exit

Example (Claude Desktop config — auto-generated by universal-mcp-fs-setup):
  {
    "mcpServers": {
      "filesystem": {
        "command": "universal-mcp-fs",
        "args": ["--allowed-dirs", "/home/user;/home/user/projects"]
      }
    }
  }

Or use npx (no global install needed):
  {
    "mcpServers": {
      "filesystem": {
        "command": "npx",
        "args": ["-y", "universal-mcp-fs", "--allowed-dirs", "/home/user"]
      }
    }
  }
`);
}

function printVersion(): void {
  try {
    const pkgPath = path.join(__dirname, "..", "package.json");
    const pkg = JSON.parse(readFileSync(pkgPath, "utf-8")) as { version: string };
    console.error(pkg.version);
  } catch {
    console.error("unknown");
  }
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);

  if (argv.includes("--help")) {
    printHelp();
    return;
  }
  if (argv.includes("--version")) {
    printVersion();
    return;
  }

  const config = loadConfig(argv);
  await startStdio(config);
}

main().catch((error) => {
  console.error("[universal-mcp-fs] Fatal error:", error);
  process.exit(1);
});
